# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2363e3ab4f233681f688bbaa16b8ef2a32c0e85c6251453579b454c4b4c169d548d120a529348a8c761b7f38e0394b1f2899b788a195d26de749be8907fa7a40

test:
  secret_key_base: 23688f51a780f56eee2dae2cec9a5fa741a7a77d477375c4d9be02699f94cb83edf73b875d836f6a4971c91e30d41bfe9ddc768de8117309635a052c6043e764

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
