# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6335461689d40d6a397de4c7c4cec6054dc2e9dd41face56784fb9c0d9ab34bf97494acb2fd049767d938d275543558be6485805e5956ec1f808dca64e5b8340

test:
  secret_key_base: d538e93d0255d943ea5727422494880cbef6bd7a96277849cd5e43a15a0c7476546c197ab766c1ba105d909c21534d5992bf02fa1754ab7fa4f3bc6a4bfc2ccf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
