# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 273f6e4211fad136624572b572c066047065db39f05c3a462182f041ea467dc249f74a8fb8363cacc48eb7b3e0f63172cd21fed138a17b3714172c920da4168a

test:
  secret_key_base: 86efba7985e56d5e76102a0b71cc4b383fc57889e891ccc6cc514f5a6b1e9635478b993d10894a9d9c7d5b1d677e57d7956598cc296f77de2710f74a5b4d93dd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
