# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 821c0e7f48bfdfa1994406a023936eb2d7844a32e6ce82fe29ea6ff3bf51c8f488f70559b5df2e395956f8a66381c6e6e2495228eb32439ca718dd6972612895

test:
  secret_key_base: 6a4084bbb16a0ff81ca1196a87d5668fa79925fe5a2fb58884811328544cf7acee1d5a62058b004d0e034514798661f9f323e4466b9440d7496076296c99793e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
